COMPETITION_NAME = "Demo Comp"
SCORING_INTERVAL = "60"

ADMIN_USERNAME = "whiteteamuser"
ADMIN_PASSWORD = "pass"

RED_TEAM_USERNAME = "redteamuser"
RED_TEAM_PASSWORD = "pass"

TEAMS = [
    {"name": "Blue Team 1", "username": "team1user1", "password": "p^ss"},
]

SERVICES = [
    {
        "name": "Team 1 Ubuntu SSH",
        "check_name": "SSHCheck",
        "port": "22",
        "points": "100",
        "matching_content": "joe is the bomb",
        "team_hosts": {"Blue Team 1": "198.18.3.180"},
        "accounts": [{"username": "joe", "password": "Joe-Blasted-Off-again2"}],
        "properties": [{"name": "commands", "value": "cat /home/joe/check.txt"}],
    },
    {
        "name": "Team 1 Ubuntu HTTP",
        "check_name": "HTTPCheck",
        "port": "80",
        "points": "100",
        "matching_content": "",
        "team_hosts": {"Blue Team 1": "198.18.3.180"},
        "accounts": [],
        "properties": [
            {"name": "useragent", "value": "Mozilla/5.0"},
            {"name": "vhost", "value": "198.18.3.180"},
            {"name": "uri", "value": "/"},
        ],
    },
    {
        "name": "Team 1 Windows RDP",
        "check_name": "RDPCheck",
        "port": "3389",
        "points": "100",
        "matching_content": "",
        "team_hosts": {"Blue Team 1": "198.18.0.78"},
        "accounts": [{"username": "Joe", "password": "Joe-Blasted-Off-again2"}],
        "properties": [],
    },
    {
        "name": "Webserver",
        "check_name": "AgentCheck",
        "port": "0",
        "points": "100",
        "matching_content": "",
        "team_hosts": {"Blue Team 1": "Webserver"},
        "accounts": [],
        "properties": [],
    },
    {
        "name": "Dbserver",
        "check_name": "AgentCheck",
        "port": "0",
        "points": "100",
        "matching_content": "",
        "team_hosts": {"Blue Team 1": "Dbserver"},
        "accounts": [],
        "properties": [],
    },
    {
        "name": "Mailserver",
        "check_name": "AgentCheck",
        "port": "0",
        "points": "100",
        "matching_content": "",
        "team_hosts": {"Blue Team 1": "Mailserver"},
        "accounts": [],
        "properties": [],
    },
    {
        "name": "Fileserver",
        "check_name": "AgentCheck",
        "port": "0",
        "points": "100",
        "matching_content": "",
        "team_hosts": {"Blue Team 1": "Fileserver"},
        "accounts": [],
        "properties": [],
    },
    {
        "name": "DNS",
        "check_name": "AgentCheck",
        "port": "0",
        "points": "100",
        "matching_content": "",
        "team_hosts": {"Blue Team 1": "DNS"},
        "accounts": [],
        "properties": [],
    },
    {
        "name": "Monitoring",
        "check_name": "AgentCheck",
        "port": "0",
        "points": "100",
        "matching_content": "",
        "team_hosts": {"Blue Team 1": "Monitoring"},
        "accounts": [],
        "properties": [],
    },
]

FLAGS = [
    {
        "type": "file",
        "platform": "nix",
        "perm": "user",
        "path": "/home/ttesterson/flag.txt",
        "content": "FLAG{demo_flag_1}",
        "start_time": "",
        "rotation_interval": "30",
        "num_rotations": "30",
        "dummy": "",
    },
    {
        "type": "file",
        "platform": "nix",
        "perm": "user",
        "path": "/home/rpeterson/flag.txt",
        "content": "FLAG{demo_flag_2}",
        "start_time": "",
        "rotation_interval": "30",
        "num_rotations": "30",
        "dummy": "",
    },
    {
        "type": "file",
        "platform": "nix",
        "perm": "user",
        "path": "/home/mjohnson/flag.txt",
        "content": "FLAG{demo_flag_3}",
        "start_time": "",
        "rotation_interval": "30",
        "num_rotations": "30",
        "dummy": "",
    },
    {
        "type": "file",
        "platform": "nix",
        "perm": "user",
        "path": "/home/sthompson/flag.txt",
        "content": "FLAG{demo_flag_4}",
        "start_time": "",
        "rotation_interval": "30",
        "num_rotations": "30",
        "dummy": "",
    },
    {
        "type": "file",
        "platform": "nix",
        "perm": "user",
        "path": "/home/kwilliams/flag.txt",
        "content": "FLAG{demo_flag_5}",
        "start_time": "",
        "rotation_interval": "30",
        "num_rotations": "30",
        "dummy": "",
    },
    {
        "type": "file",
        "platform": "nix",
        "perm": "user",
        "path": "/home/dmartin/flag.txt",
        "content": "FLAG{demo_flag_6}",
        "start_time": "",
        "rotation_interval": "30",
        "num_rotations": "30",
        "dummy": "",
    },
]
